POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
  "name": "My Tshirt",
  "price": 100.23
}

###
GET http://localhost:8080/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY5NzcyMDgsInN1YiI6Ijc5ZGE5ZTlmLWRkMzUtNDMyYS04MWUyLWRjNzk2MzFmYWNjYiJ9.JWemFBOi37VnqPjRDi_2X_cibxZrD5ZbQIUTtP1Rxk8

###

GET http://localhost:8080/products/590a4f8d-5bab-4872-95d3-ac644eaafd2d  HTTP/1.1

###
PUT http://localhost:8080/products/590a4f8d-5bab-4872-95d3-ac644eaafd2d HTTP/1.1
Content-Type: application/json

{
  "name": "My shoes",
  "price": 105.98
}

###

DELETE http://localhost:8080/products/590a4f8d-5bab-4872-95d3-ac644eaafd2d  HTTP/1.1