# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: server
        image: myjob:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: server
              key: DB_HOST
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: server
              key: MSSQL_SA_PASSWORD
        # startup probe
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          failureThreshold: 10

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          timeoutSeconds: 5

        livenessProbe: 
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
          sucessThreshold: 1

        ports:
        - containerPort: 80
          name: server
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Taipei
      restartPolicy: Always
